# Generated by Django 5.0.14 on 2026-06-23 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cita', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento_principal', models.CharField(max_length=100)),
                ('dosis_recomendada', models.CharField(max_length=50)),
                ('frecuencia_consumo', models.CharField(max_length=50)),
                ('duracion_tratamiento', models.CharField(max_length=50)),
                ('indicaciones_especiales', models.TextField(blank=True, null=True)),
                ('via_administracion', models.CharField(max_length=50)),
                ('fecha_emision', models.DateField()),
                ('requiere_control', models.BooleanField(default=False)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cita.cita')),
            ],
        ),
    ]
