# Generated by Django 5.0.14 on 2026-06-23 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medico', '0001_initial'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('motivo_consulta', models.TextField()),
                ('presion_arterial', models.CharField(max_length=20)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperatura', models.DecimalField(decimal_places=1, max_digits=4)),
                ('estado_cita', models.CharField(choices=[('Programada', 'Programada'), ('Cancelada', 'Cancelada'), ('Asistida', 'Asistida')], max_length=20)),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medico.medico')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
    ]
